name: Chocolatine

on:
  push:
    branches-ignore:
      - 'no-ga/**'
  pull_request:
    branches-ignore:
      - 'no-ga/**'

env:
  MIRROR_SSH_URL: git@github.com:EpitechPGE1-2025/G-DOP-200-COT-2-1-chocolatine-18.git
  EXECUTABLES: mysh

jobs:
  check_compilation_and_coding_style:
    name: Compilation and coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Check repo
        uses: actions/checkout@v4
      - name: Run banana-check-repo
        run: banana-check-repo
      - name: compile Project
        run: make
        timeout-minutes: 2
      - name: execute
        run: |
          if [! -x"$EXECUTABLE"]; then
            echo "Can't execute"
            exit 1
          fi
      - name: delete executable
        run: make clean
  tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: unit test
        run: make tests_run